baseURL = "/til"
title = "TIL"

# This stuff is kinda important to work with vimwiki
theme = "tale"
sectionPagesMenu = "main"
Paginate = "12"
enableEmoji = true

[params]
GitHubUser = "hectron"
# css = ["custom.css"]

[Author]
name = "Hector Rios"

[module]
  [[module.mounts]]
  source = "content/til"
  target = "content"
